const ADVERTISEMENTS_URL_PREFIX = "/advertisements"
const BUILDING_TYPE_URL_PREFIX = "/building_types"

export const ADVERTISEMENTS_URL = {
    FILTER: ADVERTISEMENTS_URL_PREFIX + "/filter"
}

export const BUILDING_TYPE_URL = {
    GET_ALL: BUILDING_TYPE_URL_PREFIX
}

export const AQAR_URL = {
    GET_BY_ID: ADVERTISEMENTS_URL_PREFIX
}